services:
  pebble:
    image: pebble
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    networks:
      acmenet:
        ipv4_address: 10.20.0.4

  agnos:
    image: agnos
    networks:
      acmenet:
        ipv4_address: 10.20.0.3

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24